### PR TITLE
RP-2379: Added guavus accelerator ansible in cdap ansible

### PR DESCRIPTION
**Pull request by jatinderjawanda**

### CODE REVIEW

**Review by jainshashank24 — COMMENTED** [review]
Hi @mohitg-guavus 
these changes need to be tested first and also if we install CDAP standalone without RAF then also it should be able to work.
As the issue i see in this is that after these changes it require CDAp Plugin RPm to be installed before we run these changes.
So in case of RAF it get installed by RAF itself but in standalone case we need to first install cdap-plugin rpm before we run the ansible.

**Comment by mohitg-guavus** [comment]
@jainshashank24 
It is the `plugin-ansible` only which downloads and installs plugins rpms. 
Therefore, to your questions -
"if we install CDAP standalone without RAF "
Yes, this will work.

"it require CDAp Plugin RPm to be installed before we run these changes"
No, this is not the case as cdap-plugin ansible will download rpms and installs them.

"So in case of RAF it get installed by RAF itself but in standalone case we need to..."
NO, this is NOT the case. cdap-plugin ansible will download rpms  in both cases.

Further, JFYI, 
`plugin-ansible` code has been modified in a way that it can now be run with RAF also and independently also 
- mode-1 : it supports fresh installation in unsecured mode
- mode-2 : it supports fresh installation in secured mode
-  mode-3 : patch installation in unsecured mode
-  mode-4 : patch installation in secured mode
plugin-ansible changes have been tested by @shashwat-tiwari-guavus and in future, any bug in cdap-plugin ansible is independent of RAF installer.

The changes that @jatinderjawanda has made is to only call plugin-ansible before enbaling security for convenience of RAF installer as JJ wanted to use mode-1 during RAF installation.

Whatever testcases you want to suggest, @jatinderjawanda may try it out with RAF installer and if anything is found broken in cdap-ansible, pls let us know.

**Comment by jainshashank24** [comment]
> @jainshashank24
> It is the `plugin-ansible` only which downloads and installs plugins rpms.

Yes i am talking about plugin installer rpm which install all other plugin rpms.
> Therefore, to your questions -
> "if we install CDAP standalone without RAF "
> Yes, this will work.

@mohitg-guavus have you try this out with standalone CDAP installation ? Because i have already faced this error when i was writing CDAP ansible and because of that only i have to remove it from CDAP ansible which was the earlier design and add it into RAF as a component.


> 
> "it require CDAp Plugin RPm to be installed before we run these changes"
> No, this is not the case as cdap-plugin ansible will download rpms and installs them.
> 
> "So in case of RAF it get installed by RAF itself but in standalone case we need to..."
> NO, this is NOT the case. cdap-plugin ansible will download rpms in both cases.
> 
> Further, JFYI,
> `plugin-ansible` code has been modified in a way that it can now be run with RAF also and independently also
> 
> * mode-1 : it supports fresh installation in unsecured mode
> * mode-2 : it supports fresh installation in secured mode
> * mode-3 : patch installation in unsecured mode
> * mode-4 : patch installation in secured mode
>   plugin-ansible changes have been tested by @shashwat-tiwari-guavus and in future, any bug in cdap-plugin ansible is independent of RAF installer.
> 
> The changes that @jatinderjawanda has made is to only call plugin-ansible before enbaling security for convenience of RAF installer as JJ wanted to use mode-1 during RAF installation.
> 
> Whatever testcases you want to suggest, @jatinderjawanda may try it out with RAF installer and if anything is found broken in cdap-ansible, pls let us know.

**Comment by mohitg-guavus** [comment]
@jainshashank24 
"Because i have already faced this error when i was writing CDAP ansible and because of that only i have to remove it from CDAP ansible "
The plugin-ansible has changed and so did you try your change with new plugin-ansible? 
You may refer to plugin-ansible [README](https://github.com/Guavus/cdap-plugins/blob/dev/RP-2379-token/cdap-plugins-solution-installer/etc/reflex-provisioner/README_cdap_accelerators.md) to check how to call it.

If u still face issue in your ansible, please raise a defect and provide details on what was the error found?

**Comment by jatinderjawanda** [comment]
> @jainshashank24
> "Because i have already faced this error when i was writing CDAP ansible and because of that only i have to remove it from CDAP ansible "
> The plugin-ansible has changed and so did you try your change with new plugin-ansible?
> You may refer to plugin-ansible [README](https://github.com/Guavus/cdap-plugins/blob/dev/RP-2379-token/cdap-plugins-solution-installer/etc/reflex-provisioner/README_cdap_accelerators.md) to check how to call it.
> 
> If u still face issue in your ansible, please raise a defect and provide details on what was the error found?

Yes, you are right @jainshashank24 !!! Plugins ansible need to be installed first if only cdap installation need to be done without RAF. This need to be tested if plugin ansible RPM is not installed before cdap installation, will cdap standalone installation break?

**Comment by mohitg-guavus** [comment]
For this standalone case, before running cdap-ansible, the `pre-requisite` could be to have both rpms installed - cdap and plugin ansibles.

**Comment by jatinderjawanda** [comment]
> For this standalone case, before running cdap-ansible, the `pre-requisite` could be to have both rpms installed - cdap and plugin ansibles.

Yes this is can be done.

**Pull request merged**
